"""Re-add location, num_beds, amenities fields

Revision ID: a98a5ba51c5b
Revises: 51bccceebb1b
Create Date: 2025-01-06 14:59:50.234427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a98a5ba51c5b'
down_revision = '51bccceebb1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('num_beds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('amenities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('amenities')
        batch_op.drop_column('num_beds')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
