"""Added acceptance deadline to contracts

Revision ID: cf373d6b1dc1
Revises: a25e69a77bbc
Create Date: 2025-01-29 13:03:06.014264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf373d6b1dc1'
down_revision = 'a25e69a77bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_acceptance_deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tenant_accepted', sa.Boolean(), nullable=True))
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('tenant_accepted')
        batch_op.drop_column('tenant_acceptance_deadline')

    # ### end Alembic commands ###
